# Generated by Django 4.1.6 on 2023-03-09 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='createdS',
            new_name='createds',
        ),
        migrations.AddField(
            model_name='purchases',
            name='createds',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchases',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
